### ISSUE TITLE
SimpleSAML\Error\NotFound after fresh install of the module

### ISSUE THREAD

**Issue by lpotherat** [tvdijen/simplesamlphp-module-monitor#24]
Hi, 

I made a fresh install of this module, and I cannot make it work.
I enabled the module, set the default template configuration, i don't use the new ui, and the link appears on the home page, but when I click on it, it seems like it searches for an index.php finle in the module, but there isn't any file named like this in the module...
Here is the error : 
SimpleSAML\Error\NotFound: The requested page 'http://127.0.0.1:8000/simplesaml/module.php/monitor/index.php' could not be found. The module 'monitor' was either not found, or wasn't enabled.

I don't know if I missed a configuration or not, any feedback would be helpful !

Thank you

**Comment by tvdijen** [comment]
Hi @lpotherat ! How exactly did you install this module?

**Comment by lpotherat** [comment]
> so my guess is that you're trying to install master instead..
Indeed, I was following the README ;-) .

Thank for your help !

For your info, I was searching for a global "health status" module, and it was the only one found in the offical simplesamlphp website :-)

**Comment by tvdijen** [comment]
Thanks a lot @lpotherat !  Let me know if you run into anything else or missing something that you think needs to be monitored :)

**Comment by lpotherat** [comment]
Hi, 
We did not use any monitoring at the end, but it's cool you're porting it to SimpleSAML 2 !
