### ISSUE TITLE
Need exposure

### ISSUE THREAD

**Issue by tvdijen** [tvdijen/simplesamlphp-module-monitor#3]
This repository needs exposure!

**Comment by tvdijen** [comment]
Message sent to mailing list to get exposure

**Comment by tvdijen** [comment]
@jaimeperez: Would you consider mentioning this on the SSP website under the 'Modules'-section?

I have an example to review here:
https://idp.moo-archive.nl/module.php/monitor/monitor.php

**Comment by jaimeperez** [comment]
Absolutely! Would you mind writing a short description of it so that I can add it to the web page?

**Comment by tvdijen** [comment]
"A SimpleSAMLphp module that can monitor authsources, metadata, certificate validity, etc. It can be easily extended with your own test cases and it can output results as HTML, XML or JSON"
How’s that sound?

**Comment by jaimeperez** [comment]
Done! 😄

https://simplesamlphp.org/modules#monitor

**Comment by jaimeperez** [comment]
BTW, some unrelated comments:

* On each section header, the black text over red background is quite hard to read. It would be better if text was white in that case.

* Maybe rename the script from `monitor.php` to `index.php`? That way, the canonical URL could be `/whatever/path/to/simplesaml/modules.php/monitor/`, which looks cleaner IMHO.

* I can help with translations into spanish, if you want 😉 (although I can't see there are any translations yet).
